name: Build and convert video using FFmpeg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg libopencore-amrnb-dev libopencore-amrwb-dev
          wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
          tar -zxvf yasm-1.3.0.tar.gz
          cd yasm-1.3.0
          ./configure
          make -j$(nproc)
          sudo make install
      - name: Build AMR
        run: |
          wget http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.6.tar.gz
          tar -zxvf opencore-amr-0.1.6.tar.gz
          cd opencore-amr-0.1.6
          ./configure --prefix=/usr --disable-shared
          make -j$(nproc)
          sudo make install
      - name: Build FFmpeg with AMR codec
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          ./configure --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-version3
          make -j$(nproc)
          sudo make install
      - name: Test ffmpeg
        run: |
          ffmpeg -version
