name: linux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pagmo2/llvm_manylinux_2_28_x86_64

    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package
        run: |
          XMAKE_ROOT=y xmake config --yes --verbose --plat=linux --arch=x86_64 --toolchain=clang

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-gnu
          path: build/package
          if-no-files-found: error
