name: linux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20 all
          xmake config --yes --verbose --plat=linux --arch=x86_64 --toolchain=clang-20

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-gnu
          path: build/package
          if-no-files-found: error
