name: windows

permissions:
  contents: write

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # WyriHaximus/github-action-get-previous-tag@master need it
          fetch-depth: 0

      - name: Package
        run: |
          xmake config --yes --verbose --plat=windows --arch=x64 --mode=release

      - name: Get Previous tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/package/x64-windows-msvc-release.7z
          asset_name: build/package/x64-windows-msvc-release.7z
          tag: ${{ steps.previous_tag.outputs.tag }}
          overwrite: true
